<?php

include_once('os_slideshow_lite.features.inc');

/**
 * Implementation of hook_block().
 */
function os_slideshow_lite_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks = array();
      $result = db_query("SELECT nid FROM {node} WHERE type = '%s'",
        array(':type' => 'slideshow'));
      while ($row = db_fetch_array($result)) {
        $node = node_load($row['nid']);
        if (!empty($node->field_slideshow_machine_name[0]['value'])) {
          $blocks[$node->field_slideshow_machine_name[0]['value']] = array(
            'info' => $node->title,
            'cache' => BLOCK_NO_CACHE,
          );
        }
      }
      return $blocks;
    case 'view':
      $result = db_query("SELECT nid FROM {content_type_slideshow} WHERE field_slideshow_machine_name_value = '%s'",
        array(':machine_name' => $delta));
      $output = '';
      if ($nid = db_result($result)) {
        $output = views_embed_view('os_slideshow_lite', 'default', $nid);
      }
      return array('subject' => '', 'content' => $output);
  }
}

